version: 0.2

run-as: root

phases:
  build:
    commands:
      - pwsh
      - Install-Module Pester -Force
      - Import-Module Pester -PassThru
      - echo "Remember to change directories in real thing."
      - Invoke-Pester
      - exit

artifacts:
  files:
    - '**/*'
